version: "3.7"

services:

    nginx:
        image: nginx:latest
        working_dir: /usr/share/nginx/html
        container_name: nginx
        volumes:
            - ./index.html:/usr/share/nginx/html/index.html
            - ./site.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "80:80"